local Proto = Proto
local ProtoField = ProtoField
local base = base
local module = {}
----------------------------------------------------------------
function module:messageName()
  return 'FsHlC_SSubCellGroupSetupReq'
end
function module:messageId()
  return 0x7004
end
----------------------------------------------------------------
local FSHLC_SSUBCELLGROUPSETUPREQ = Proto('FsHlC_SSubCellGroupSetupReq', 'FSHLC_SSUBCELLGROUPSETUPREQ')
local FsHlC_SSubCellGroupSetupReq = FSHLC_SSUBCELLGROUPSETUPREQ.fields
FsHlC_SSubCellGroupSetupReq.messageType = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq.messageType', 'messageType', base.HEX)
FsHlC_SSubCellGroupSetupReq.subcellGroupId = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq.subcellGroupId', 'subcellGroupId', base.HEX)
FsHlC_SSubCellGroupSetupReq.subcellGroupId_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq.subcellGroupId_padding', 'subcellGroupId_padding', base.DEC)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.ulSchedTimeInterval = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.ulSchedTimeInterval', 'ulSchedTimeInterval', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.ulSchedTimeInterval_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.ulSchedTimeInterval_padding', 'ulSchedTimeInterval_padding', base.HEX)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ANTPORTBRSIDLIST = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ANTPORTBRSIDLIST')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ANTPORTBRSIDLIST.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList.antPortBrsIdList_length = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList.antPortBrsIdList_length', 'antPortBrsIdList_length', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList.antPortBrsIdList_values = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList.antPortBrsIdList_values', 'antPortBrsIdList_values', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.actProactUlScheduling = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.actProactUlScheduling', 'actProactUlScheduling', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxNumRrcBfGr = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxNumRrcBfGr', 'maxNumRrcBfGr', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.addNumRrcBfCh = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.addNumRrcBfCh', 'addNumRrcBfCh', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.addNumRrcBfCh_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.addNumRrcBfCh_padding', 'addNumRrcBfCh_padding', base.DEC)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ULLINKADAPTATION = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ULLINKADAPTATION')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ULLINKADAPTATION.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.actUlla = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.actUlla', 'actUlla', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.blerTarget = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.blerTarget', 'blerTarget', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMax = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMax', 'deltaSinrMax', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMin = ProtoField.int16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMin', 'deltaSinrMin', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMin_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMin_padding', 'deltaSinrMin_padding', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrStepDown = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrStepDown', 'deltaSinrStepDown', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.iniMcs = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.iniMcs', 'iniMcs', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.iniMcs_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.iniMcs_padding', 'iniMcs_padding', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.maxCodeRate = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.maxCodeRate', 'maxCodeRate', base.HEX)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_DLLINKADAPTATION = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_DLLINKADAPTATION')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_DLLINKADAPTATION.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.actDlla = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.actDlla', 'actDlla', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.blerTarget = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.blerTarget', 'blerTarget', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMax = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMax', 'deltaCqiMax', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMin = ProtoField.int16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMin', 'deltaCqiMin', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMin_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMin_padding', 'deltaCqiMin_padding', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiStepDown = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiStepDown', 'deltaCqiStepDown', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.iniMcs = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.iniMcs', 'iniMcs', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.iniMcs_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.iniMcs_padding', 'iniMcs_padding', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.maxCodeRate = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.maxCodeRate', 'maxCodeRate', base.HEX)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subcellList_length = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subcellList_length', 'subcellList_length', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subCellId = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subCellId', 'subCellId', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subCellId_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subCellId_padding', 'subCellId_padding', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.l2RtPoolId = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.l2RtPoolId', 'l2RtPoolId', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.l1PoolId = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.l1PoolId', 'l1PoolId', base.HEX)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST_CELLPARAMETERSIE = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST_CELLPARAMETERSIE')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST_CELLPARAMETERSIE.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ngutranCellId = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ngutranCellId', 'ngutranCellId', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.physCellId = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.physCellId', 'physCellId', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.physCellId_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.physCellId_padding', 'physCellId_padding', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ccPosId = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ccPosId', 'ccPosId', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.numAntPortsBrs = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.numAntPortsBrs', 'numAntPortsBrs', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.prachUrootValue = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.prachUrootValue', 'prachUrootValue', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ulMimoMode = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ulMimoMode', 'ulMimoMode', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.dlMimoMode = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.dlMimoMode', 'dlMimoMode', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.dlMimoMode_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.dlMimoMode_padding', 'dlMimoMode_padding', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxUlHarqTx = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxUlHarqTx', 'maxUlHarqTx', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxHarqMsg3Tx = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxHarqMsg3Tx', 'maxHarqMsg3Tx', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxDlHarqTx = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxDlHarqTx', 'maxDlHarqTx', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxDlHarqTx_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxDlHarqTx_padding', 'maxDlHarqTx_padding', base.DEC)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.brsTransmissionPeriod = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.brsTransmissionPeriod', 'brsTransmissionPeriod', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.brsTransmissionPeriod_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.brsTransmissionPeriod_padding', 'brsTransmissionPeriod_padding', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.beamReferenceSignalPower = ProtoField.int16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.beamReferenceSignalPower', 'beamReferenceSignalPower', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.pssSssEssxPbchPower = ProtoField.int16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.pssSssEssxPbchPower', 'pssSssEssxPbchPower', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlRlcEvalPeriod = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlRlcEvalPeriod', 'dlRlcEvalPeriod', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.preambleFormat = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.preambleFormat', 'preambleFormat', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.prachConfiguration = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.prachConfiguration', 'prachConfiguration', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.prachConfiguration_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.prachConfiguration_padding', 'prachConfiguration_padding', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.cfoFilterCoefficient = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.cfoFilterCoefficient', 'cfoFilterCoefficient', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.rxScalingFactor = ProtoField.int16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.rxScalingFactor', 'rxScalingFactor', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.raResponseWindowSize = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.raResponseWindowSize', 'raResponseWindowSize', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.macContentionResTimer = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.macContentionResTimer', 'macContentionResTimer', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.totalPA = ProtoField.uint32('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.totalPA', 'totalPA', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlPcrsAntennaPortNumber = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlPcrsAntennaPortNumber', 'dlPcrsAntennaPortNumber', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.actFeatureBeamTracking = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.actFeatureBeamTracking', 'actFeatureBeamTracking', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tCPGuard = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tCPGuard', 'tCPGuard', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tFsHLPathSwitch = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tFsHLPathSwitch', 'tFsHLPathSwitch', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tFsHLPathSwitch_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tFsHLPathSwitch_padding', 'tFsHLPathSwitch_padding', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tProhibBsiReq = ProtoField.uint16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tProhibBsiReq', 'tProhibBsiReq', base.HEX)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_DLTDPRIO = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_DLTDPRIO')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_DLTDPRIO.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlRachMsg2 = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlRachMsg2', 'prioDlRachMsg2', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqTransMsg4 = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqTransMsg4', 'prioDlHarqTransMsg4', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransSrb1 = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransSrb1', 'prioDlHarqRetransSrb1', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransSrb2 = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransSrb2', 'prioDlHarqRetransSrb2', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransDrb = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransDrb', 'prioDlHarqRetransDrb', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlTimAdv = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlTimAdv', 'prioDlTimAdv', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlSrb1Traffic = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlSrb1Traffic', 'prioDlSrb1Traffic', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlSrb2Traffic = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlSrb2Traffic', 'prioDlSrb2Traffic', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlDrbTraffic = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlDrbTraffic', 'prioDlDrbTraffic', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlCsi = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlCsi', 'prioDlCsi', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlBsiSr = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlBsiSr', 'prioDlBsiSr', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlBsiSr_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlBsiSr_padding', 'prioDlBsiSr_padding', base.DEC)
local FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_ULTDPRIO = Proto('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio', 'FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_ULTDPRIO')
local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio = FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_ULTDPRIO.fields
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlRachMsg3 = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlRachMsg3', 'prioUlRachMsg3', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransRach = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransRach', 'prioUlHarqRetransRach', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransSrb = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransSrb', 'prioUlHarqRetransSrb', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransDrb = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransDrb', 'prioUlHarqRetransDrb', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlSrResp = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlSrResp', 'prioUlSrResp', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlSrbTraffic = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlSrbTraffic', 'prioUlSrbTraffic', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlDrbTraffic = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlDrbTraffic', 'prioUlDrbTraffic', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlProactSched = ProtoField.uint8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlProactSched', 'prioUlProactSched', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlUlDataSubframeRatio = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlUlDataSubframeRatio', 'dlUlDataSubframeRatio', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlUlDataSubframeRatio_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlUlDataSubframeRatio_padding', 'dlUlDataSubframeRatio_padding', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.pneRbgThreshold = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.pneRbgThreshold', 'pneRbgThreshold', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.ePbchTransmissionPeriod = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.ePbchTransmissionPeriod', 'ePbchTransmissionPeriod', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.ePbchTransmissionPeriod_padding = ProtoField.int8('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.ePbchTransmissionPeriod_padding', 'ePbchTransmissionPeriod_padding', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPrach = ProtoField.int16('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPrach', 'dtxThresholdPrach', base.DEC)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPuschSingleLayerList = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPuschSingleLayerList', 'dtxThresholdPuschSingleLayerList', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPuschTwoLayerList = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPuschTwoLayerList', 'dtxThresholdPuschTwoLayerList', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPucchSingleLayerList = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPucchSingleLayerList', 'dtxThresholdPucchSingleLayerList', base.HEX)
FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPucchTwoLayerList = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPucchTwoLayerList', 'dtxThresholdPucchTwoLayerList', base.HEX)
FsHlC_SSubCellGroupSetupReq.actDigitalBF = ProtoField.int8('FsHlC_SSubCellGroupSetupReq.actDigitalBF', 'actDigitalBF', base.DEC)
FsHlC_SSubCellGroupSetupReq.actDigitalBF_padding = ProtoField.bytes('FsHlC_SSubCellGroupSetupReq.actDigitalBF_padding', 'actDigitalBF_padding', base.HEX)
----------------------------------------------------------------
function module:dissector(buffer, offset, pinfo, tree, msglen)
  local subtree = tree:add (FSHLC_SSUBCELLGROUPSETUPREQ, buffer())
  subtree:set_text('FsHlC_SSubCellGroupSetupReq')
  subtree:add_le (FsHlC_SSubCellGroupSetupReq.messageType, buffer(offset, 2))
  offset = offset + 2
  subtree:add_le (FsHlC_SSubCellGroupSetupReq.subcellGroupId, buffer(offset, 1))
  offset = offset + 1
  subtree:add_le (FsHlC_SSubCellGroupSetupReq.subcellGroupId_padding, buffer(offset, 1))
  offset = offset + 1
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree = subtree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.ulSchedTimeInterval, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.ulSchedTimeInterval_padding, buffer(offset, 2))
  offset = offset + 2
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdListTree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ANTPORTBRSIDLIST, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdListTree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdListTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList.antPortBrsIdList_length, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdListTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_antPortBrsIdList.antPortBrsIdList_values, buffer(offset, ( (msglen >= 512) and 512 or (msglen-offset) )))
  offset = offset + ( (msglen >= 512) and 512 or (msglen-offset) )
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.actProactUlScheduling, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxNumRrcBfGr, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.addNumRrcBfCh, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.addNumRrcBfCh_padding, buffer(offset, 1))
  offset = offset + 1
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_ULLINKADAPTATION, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.actUlla, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.blerTarget, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMax, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMin, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrMin_padding, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.deltaSinrStepDown, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.iniMcs, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.iniMcs_padding, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_ulLinkAdaptation.maxCodeRate, buffer(offset, 2))
  offset = offset + 2
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_DLLINKADAPTATION, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.actDlla, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.blerTarget, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMax, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMin, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiMin_padding, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.deltaCqiStepDown, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.iniMcs, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.iniMcs_padding, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptationTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_dlLinkAdaptation.maxCodeRate, buffer(offset, 2))
  offset = offset + 2
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subcellList_length, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subCellId, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.subCellId_padding, buffer(offset, 3))
  offset = offset + 3
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.l2RtPoolId, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList.l1PoolId, buffer(offset, 4))
  offset = offset + 4
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellListTree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_SUBCELLLIST_CELLPARAMETERSIE, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ngutranCellId, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.physCellId, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.physCellId_padding, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ccPosId, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.numAntPortsBrs, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.prachUrootValue, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.ulMimoMode, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.dlMimoMode, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_subcellList_cellParametersIE.dlMimoMode_padding, buffer(offset, 3))
  offset = 16944
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxUlHarqTx, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxHarqMsg3Tx, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxDlHarqTx, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE.maxDlHarqTx_padding, buffer(offset, 1))
  offset = offset + 1
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIETree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.brsTransmissionPeriod, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.brsTransmissionPeriod_padding, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.beamReferenceSignalPower, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.pssSssEssxPbchPower, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlRlcEvalPeriod, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.preambleFormat, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.prachConfiguration, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.prachConfiguration_padding, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.cfoFilterCoefficient, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.rxScalingFactor, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.raResponseWindowSize, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.macContentionResTimer, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.totalPA, buffer(offset, 4))
  offset = offset + 4
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlPcrsAntennaPortNumber, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.actFeatureBeamTracking, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tCPGuard, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tFsHLPathSwitch, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tFsHLPathSwitch_padding, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.tProhibBsiReq, buffer(offset, 2))
  offset = offset + 2
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_DLTDPRIO, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlRachMsg2, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqTransMsg4, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransSrb1, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransSrb2, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlHarqRetransDrb, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlTimAdv, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlSrb1Traffic, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlSrb2Traffic, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlDrbTraffic, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlCsi, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlBsiSr, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_dlTdPrio.prioDlBsiSr_padding, buffer(offset, 1))
  offset = offset + 1
  local FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree = FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add (FSHLC_SSUBCELLGROUPSETUPREQ_SUBCELLGROUPPARAMETERSIE_NODEBPARAMETERSIE_ULTDPRIO, buffer(offset))
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:set_text('FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio')
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlRachMsg3, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransRach, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransSrb, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlHarqRetransDrb, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlSrResp, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlSrbTraffic, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlDrbTraffic, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrioTree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE_ulTdPrio.prioUlProactSched, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlUlDataSubframeRatio, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dlUlDataSubframeRatio_padding, buffer(offset, 3))
  offset = offset + 3
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.pneRbgThreshold, buffer(offset, ( (msglen >= 16) and 16 or (msglen-offset) )))
  offset = offset + ( (msglen >= 16) and 16 or (msglen-offset) )
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.ePbchTransmissionPeriod, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.ePbchTransmissionPeriod_padding, buffer(offset, 1))
  offset = offset + 1
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPrach, buffer(offset, 2))
  offset = offset + 2
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPuschSingleLayerList, buffer(offset, ( (msglen >= 52) and 52 or (msglen-offset) )))
  offset = offset + ( (msglen >= 52) and 52 or (msglen-offset) )
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPuschTwoLayerList, buffer(offset, ( (msglen >= 52) and 52 or (msglen-offset) )))
  offset = offset + ( (msglen >= 52) and 52 or (msglen-offset) )
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPucchSingleLayerList, buffer(offset, ( (msglen >= 44) and 44 or (msglen-offset) )))
  offset = offset + ( (msglen >= 44) and 44 or (msglen-offset) )
  FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIETree:add_le (FsHlC_SSubCellGroupSetupReq_subcellGroupParametersIE_nodeBParametersIE.dtxThresholdPucchTwoLayerList, buffer(offset, ( (msglen >= 44) and 44 or (msglen-offset) )))
  offset = offset + ( (msglen >= 44) and 44 or (msglen-offset) )
  subtree:add_le (FsHlC_SSubCellGroupSetupReq.actDigitalBF, buffer(offset, 1))
  offset = offset + 1
  subtree:add_le (FsHlC_SSubCellGroupSetupReq.actDigitalBF_padding, buffer(offset, 3))
  offset = offset + 3
end
----------------------------------------------------------------
return module
